name: Build Kivy APK Simples

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
        pip install --upgrade Cython==0.29.37 buildozer

    - name: Add PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Accept licenses and install build-tools
      run: |
        # Cria SDK manualmente
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
        unzip -q cmdline.zip -d $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        # Aceita todas licen√ßas
        yes | sdkmanager --licenses
        # Instala build-tools e platform
        yes | sdkmanager "build-tools;33.0.0" "platforms;android-33" "platform-tools"

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: spotify-apk
        path: bin/*.apk
        retention-days: 7
